# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LGHTSG' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LGHTSG
  pod 'NMapsMap'
  pod 'DropDown'
  pod 'Charts'
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa'
  pod 'Kingfisher', '~> 6.0'
end
